1. Have an running instance of postgresql
2. Edit the `development.env` accordingly
3. Build the docker-image `docker build .`
4. Create the docker container: `docker create --env-file=development.env --name seee -p 3008:3000 <hash of the image>`
5. Start the container `docker start seee`
6. Create the database, if needed, `docker exec seee bundle exec rake db:create`
7. Migrate the database, if needed, `docker exec seee bundle exec rake db:migrate qc:update`
8. Done! Visit `localhost:3008`
