########################################################################
# HOW 2 CONFIG
########################################################################
# This is the default configuration file, which is checked into the
# repository. It will load the system and user configuration files, if
# they exist, from the following locations:
<% system_config = "/etc/gnt-eval-database.yml" %>
<% user_config =  "~/.gnt-eval-database.yml" %>
# The user’s one takes precedence over the system wide one which takes
# precedence over this default file. To start your own configuration
# file, simply copy the contents below.
########################################################################
default: &default
  adapter: <%= ENV['PRODUCTION_DATABASE_ADAPTER'] %>
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE_DATABASE'] %>

test:
  <<: *default
  database: kummerkasten_test
production:
  <<: *default
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  port: <%= ENV['PRODUCTION_DATABASE_PORT'] %>
  database: <%= ENV['PRODUCTION_DATABASE_DATABASE'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>

# Load configuration files from other directories.
<% system_config = File.expand_path(system_config) %>
<%= IO.read(system_config) if File.exist?(system_config) %>


<% begin; user_config = File.expand_path(user_config) %>
<%= IO.read(user_config) if File.exist?(user_config) %>
<% rescue; end %>
