# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 192f4a28cc3d1c8c316ac5b0f884482359892fb2c6ec874df13ab75517a87f04b7e9a54cdf0329c22b68ced3b5ff84974c4544655521bfa3d4c7e960d5d887a6

test:
  secret_key_base: e3f3961e9cae667c1fadcef1238ef873332fcb609285146c53e714926913cbc0eedcf28a34e980c1eb54fc2e79c93e23e95f65c3c05dfa3212d418c31fedc66a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
